In [3]:
import sys
from pathlib import Path

# Force notebook to recognize project root
import os
ROOT = Path(os.getcwd()).resolve().parents[0] # one level up from tests/
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

import pandas as pd
from src.inference_pipeline.inference import predict

# Load a few rows of already preprocessed data
sample_path = ROOT / "data/processed/cleaning_eval.csv"
df = pd.read_csv(sample_path).sample(5, random_state=42).reset_index(drop=True)

print("Input sample:")
display(df.head(1))

# Run inference
preds_df = predict(df)
print("✅ Predictions returned")
display(preds_df[["predicted_price"]].head(1))

Input sample:

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,...,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,2021-07-31,258528.0,259900.0,145.39616,140.979244,104.0,98.0,107.0,66.0,48.0,...,182900.0,10937.0,250.0,20604.0,20604.0,10007.0,255300.562038,"cincinnati, oh-ky-in",39.0811,-84.4646

⚠️ Skipping lat/lng merge: metros file not provided or not found.
✅ Dropped 0 duplicate rows (excluding date/year).
✅ Removed 0 rows with median_list_price > 19M.
✅ Predictions returned

   predicted_price
0    234082.796875

In [6]:
preds_df["predicted_price"]

0    234082.796875
1    426309.375000
2    208739.546875
3    541214.875000
4    666718.125000
Name: predicted_price, dtype: float32

In [7]:
preds_df["actual_price"]

0    255300.562038
1    450603.296700
2    189474.969209
3    504649.454265
4    699558.033278
Name: actual_price, dtype: float64